"""User table

Revision ID: 44c87365175f
Revises: 
Create Date: 2020-03-03 02:13:47.882419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c87365175f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('Module')
    op.drop_table('tb1')
    op.drop_table('User')
    op.drop_table('HouseKeeper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HouseKeeper',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('moduleId', sa.INTEGER(), nullable=False),
    sa.Column('courseId', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uname', sa.TEXT(), nullable=False),
    sa.Column('pwd', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('is_authenticated', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.INTEGER(), nullable=False),
    sa.Column('is_anonymous', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb1',
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True)
    )
    op.create_table('Module',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
